# Generated by Django 4.2.11 on 2024-03-06 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_event_current_slots_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
